### ISSUE TITLE
swayosd-libinput-backend.service does not exist.

### ISSUE THREAD

**Issue by nikza03** [mooncoffee1/gruvbox-hyprland#1]
Hello! First, I want to express my appreciation for your rice; it's fantastic. I've been trying to install it on my laptop, but I encountered an issue. When I attempt to execute the following command:
```
sudo systemctl enable --now swayosd-libinput-backend.service
```
I receive the following error message:
```
Failed to enable unit: Unit file swayosd-libinput-backend.service does not exist.
```
I would greatly appreciate your assistance with this matter. Once again, I want to emphasize how much I admire your work. Thank you in advance!

**Comment by mooncoffee1** [comment]
sorry if im late, u first need to install swayosd-git, do this

``yay -S swayosd-git ``

then retry the systemctl command
